import React, { ReactNode } from 'react';
import Head from 'next/head';

import Header from './header';
import Footer from './footer';

interface PropsTypes {
  children: ReactNode;
  title: string;
}
const Layout: React.FC<PropsTypes> = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <base href="/" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <div>{children}</div>
      <Footer />
    </>
  )
}

export default Layout;