import Head from 'next/head'
import Layout from '@/components/layout';

export default function Home() {
  return (
    <Layout title="Generated by create next app">
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-success'>Hello NextJs!</div>
    </Layout>
  )
}
